apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miniapp
  template:
    metadata:
      labels:
        app: miniapp
    spec:
      containers:
        - name: miniapp
          image: your_dockerhub_username/miniapp:latest # замените на ваш образ
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: tls-secret
              mountPath: "/certs"
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: tls-secret
          secret:
            secretName: miniapp-tls
