version: "3.8"

services:
  web:
    build: ./
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /etc/letsencrypt/live/pxmx-home.ddns.net/fullchain.pem:/app/fullchain.pem
      - /etc/letsencrypt/live/pxmx-home.ddns.net/privkey.pem:/app/privkey.pem
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=mini_app_db
    depends_on:
      - db
    command: ["./wait-for-db.sh", "node", "index_https_manag.js"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
