version: "3.8"

services:
  web:
    build: ./
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /etc/letsencrypt/live/pxmx-home.ddns.net/fullchain.pem:/app/fullchain.pem
      - /etc/letsencrypt/live/pxmx-home.ddns.net/privkey.pem:/app/privkey.pem
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=mini_app_db
      - TOKEN=7892668257:AAFMUMi-eJk9ionZT-JcKVAmv0xcGfN_cDU
      - WEB_URL=https://pxmx-home.ddns.net/
      - CHAT_ID=1327132620
    depends_on:
      db:
        condition: service_healthy
    command: ["/usr/local/bin/update-and-run"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
