version: "3.8"

services:
  web:
    build: ./
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /etc/letsencrypt/live/pxmx-home.ddns.net/fullchain.pem:/app/fullchain.pem
      - /etc/letsencrypt/live/pxmx-home.ddns.net/privkey.pem:/app/privkey.pem
    command: [/bin/bash, "./update_and_run.sh"]
