version: "3.8"

services:
  web:
    build: ./
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /etc/letsencrypt/live/pxmx-home.ddns.net/cert.pem:/app/cert.pem
      - /etc/letsencrypt/live/pxmx-home.ddns.net/privkey.pem:/app/key.pem
    command: ["./update_and_run.sh"]
